ray: final_main.cpp
	g++ -g final_main.cpp -o ray

ray1: main_1.cpp
	g++ -g main_1.cpp -o ray1

ray2: main_2.cpp
	g++ -g main_2.cpp -o ray2

ray3: main_3.cpp
	g++ -g main_3.cpp -o ray3

ray4: main_4.cpp
	g++ -g main_4.cpp -o ray4

ray5: main_5.cpp
	g++ -g main_5.cpp -o ray5

ray6: main_6.cpp
	g++ -g main_6.cpp -o ray6

ray7: main_7.cpp
	g++ -g main_7.cpp -o ray7

ray8: main_8.cpp
	g++ -g main_8.cpp -o ray8

ray9: main_9.cpp
	g++ -g main_9.cpp -o ray9

ray10: main_10.cpp
	g++ -g main_10.cpp -o ray10

ray11: main_11.cpp
	g++ -g main_11.cpp -o ray11

clean:
	rm -f ray[1-11] *~

